feat(geopandas support): return GeoDataFrame if geopandas is installed
DOI-USGS/dataretrieval-python pull request #143
Opened 2024-07-16 18:28 UTC by jlarsen-usgs

2024-07-16 18:50 UTC, thodson-usgs requested changes
Very nice. Even better if you added a unit test, but I'll approve it either way.

Otherwise, I had one comment.

2024-07-16 18:50 UTC, thodson-usgs commented on dataretrieval/nwis.py
> +    if gpd is not None:
Does this remove the original lat/lon column?
If so (and perhaps either way), we should make this conversion optional, so that we don't break existing codes.

2024-07-16 18:54 UTC, jlarsen-usgs commented on dataretrieval/nwis.py
> +    if gpd is not None:
This maintains the original lat/long columns. This PR just builds a geometry field from that data and creates a geodataframe. I can add a unit test that checks the return type

2024-07-16 21:47 UTC, jlarsen-usgs commented on dataretrieval/nwis.py
> +    if gpd is not None:
Updated tests for geopandas support

2024-07-19 15:56 UTC, thodson-usgs approved these changes
looks good!

2024-07-19 15:56 UTC, merged